set timeout 1

proc run_test { demo_name expected_output } {
	spawn "pdp1"
	send "set cpu mdv\n"
	send "attach ptr $demo_name/main.rim\n"
	expect {
		"PTR: creating new file"	{ fail "$demo_name: Didn't find the RIM tape file\n" }
		"sim>"				{ pass "$demo_name: Successfully loaded the RIM tape file\n" }
		default				{ fail "$demo_name: Test failed unexpectedly\n" }
	}
	
	send "boot ptr\n"
	expect {
		"$expected_output"		{ pass "$demo_name: Encountered expected output\n" }
		default				{ fail "$demo_name: Didn't encounter expected output\n" }
	}
	expect {
		-re "HALT instruction,.*"	{ pass "$demo_name: Program finished running normally\n" }
		default				{ fail "$demo_name: Program halted unexpectedly\n" }
	}

	send "quit\n"
}

run_test "asm-print-x" "x"
run_test "asm-hello-world" "hello, world"
run_test "c-print-x" "xx"
run_test "c-print-struct" "xyz"
run_test "c-print-array" "xyzxyzxyzxyz"
run_test "c-print-for-loop" "xxxxyxxx"
run_test "c-test-comparison" "aceg"
run_test "c-test-arith" "xx"
run_test "c-test-recursion" "xxxxxxxxxxxxxxxxxxxx"
run_test "c-print-fibonacci" "0,1,1,2,3,5,8,31,12,43,55,98,441,332,773,016,789,7951,4852,1814,"
